import { useEffect, useState } from 'react';
import { VideoRoom } from '../components/VideoRoom';
import { VideoProvider } from '../context/VideoProvider';
import { getToken } from '../../../api/client';

/**
 * Demo page showing how to use the reusable video module.
 * In a real application, you would replace the mock fetch with a call to your
 * own backend that returns a LiveKit token (generated by the video module's
 * routes).
 */
export const VideoDemoPage = () => {
  const [token, setToken] = useState<string | null>(null);
  const [url, setUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // In a real app, you might get roomId from route params or context.
  const roomId = 'demo-room-123';

  useEffect(() => {
    const fetchToken = async () => {
      try {
        setLoading(true);
        setError(null);
        // Example: call your backend endpoint that uses the video module to generate a token.
        // Adjust the URL to match your API.
        const resp = await fetch(`/api/v1/video/rooms/${roomId}/token`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            // Include auth token if available
            Authorization: `Bearer ${getToken() ?? ''}`,
          },
          body: JSON.stringify({
            participant_id: 'user-demo-456',
            role: 'guest', // or 'host' depending on the user
            ttl: 3600,
            metadata: { displayName: 'Demo User' },
          }),
        });
        if (!resp.ok) {
          throw new Error(`Failed to fetch token: ${resp.status}`);
        }
        const data = await resp.json();
        // Assuming the backend returns { token, url } as per TokenResponse
        setToken(data.token);
        setUrl(data.url ?? undefined);
      } catch (e) {
        setError(e instanceof Error ? e.message : 'Unknown error');
      } finally {
        setLoading(false);
      }
    };

    fetchToken();
  }, [roomId]);

  if (loading) {
    return <div>Loading video token…</div>;
  }
  if (error) {
    return <div style={{ color: '#d00', padding: '20px' }}>Error: {error}</div>;
  }
  if (!token) {
    return <div>Waiting for token…</div>;
  }

  return (
    <VideoProvider token={token} url={url} autoJoin>
      <VideoRoom
        token={token}
        url={url}
        onLeave={() => {
          // Optionally navigate back to a list page
          console.log('User left the room');
        }}
        showLocalPreview={true}
      >
        {/* You could add custom content here, e.g., a chat sidebar */}
      </VideoRoom>
    </VideoProvider>
  );
};